name: me_empresta_ai
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  sqflite: ^2.0.3+1
  floor: ^1.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.3.0
  build_runner: ^2.1.2
flutter:
  uses-material-design: true
  assets:
    - images/db.svg
    - images/firebase-icon.svg
    - images/firebase.svg
    - images/sqlite-icon.svg

  # To add assets to your application, add an assets section, like this: